"""Render the panel's real markup against its real stylesheet, for eyeballing.

`webviewMain.test.ts` proves every element `main.js` binds to exists, but no
test can tell you the popover looks wrong. This lifts the template out of
`getHtml()` verbatim, points it at `media/style.css`, forces the popover open
and paints a plausible signed-in state, so what you open in a browser is the
panel rather than an impression of it.

A paint check only: no CSP, no `main.js`, nothing interactive. Re-run after any
change to `getHtml()`.

    python docs/mockups/make-preview.py
"""
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "extension" / "src" / "sidebarProvider.ts"
OUT = ROOT / "docs" / "mockups" / "panel-preview.html"

NOTE = """<!-- GENERATED by docs/mockups/make-preview.py — do not hand-edit.
     The real markup from sidebarProvider.getHtml(), against the real
     media/style.css, with the popover forced open and a signed-in state
     painted in. A paint check: no CSP, no main.js, nothing interactive.

     Same idea as .superpowers/sdd/2026-08-09-edupeer-panel-redesign/
     panel-frame.html, which reconstructs the markup by hand where this
     lifts it from getHtml(). -->
"""

# The only things VS Code supplies that a browser cannot, set to the editor's
# defaults. Not cosmetic: `--display` and `--sans` (style.css:74-75) reference
# `var(--vscode-font-family)` with NO fallback, so in a browser the
# substitution is guaranteed-invalid and every `font-family: var(--sans)`
# becomes invalid at computed-value time — the panel silently renders in the
# browser's default face instead of Geist and Bricolage. The size tokens all
# carry `, 13px`, so only the two font stacks are affected.
VSCODE_STUBS = """
<style>
  :root {
    --vscode-font-family: "Segoe WPC", "Segoe UI", system-ui, sans-serif;
    --vscode-font-size: 13px;
    --vscode-editor-font-family: Consolas, "Cascadia Mono", monospace;
  }
</style>
"""

# A few real rows, so the disclosure is showing something with a gutter rather
# than an empty box. `renderLines()` builds these at runtime; this is the same
# shape by hand, because the preview runs no script.
PREVIEW_LINES = (
    '<pre id="codeSnippet" class="ctx__pre" tabindex="0">'
    + "".join(
        '<span class="ln%s"><span class="ln__no">%d</span>'
        '<span class="ln__text">%s</span></span>'
        % (" is-cursor" if n == 14 else "", n, text)
        for n, text in [
            (12, "def last_index(items):"),
            (13, "    n = len(items)"),
            (14, "    for i in range(n):"),
            (15, "        if items[i + 1] == 0:"),
            (16, "            return i"),
        ]
    )
    + "</pre>"
)

# (find, replace). Everything here is presentation state that `main.js` would
# normally set from a message; none of it changes the markup under review.
SUBSTITUTIONS = [
    ('${asset("style.css")}', "../../extension/media/style.css"),
    ('<div class="pop" id="prefsPop" role="dialog" aria-label="Account and preferences" hidden>',
     '<div class="pop" id="prefsPop" role="dialog" aria-label="Account and preferences">'),
    ('id="accountInitials" aria-hidden="true">?<', 'id="accountInitials" aria-hidden="true">IS<'),
    ('<span class="avatar__pip" id="accountPip" aria-hidden="true"></span>',
     '<span class="avatar__pip" id="accountPip" aria-hidden="true" hidden></span>'),
    ('id="popName">Working anonymously<', 'id="popName">Ibrahim Saif<'),
    ('id="popMail">Your streak and badges live on this machine only.<',
     'id="popMail">ahmed@karzo.com<'),
    ('<div class="pop__signin" id="popSignInWrap">',
     '<div class="pop__signin" id="popSignInWrap" hidden>'),
    ('id="signOutBtn" hidden>', 'id="signOutBtn">'),
    ('id="popBackend"></span>', 'id="popBackend">edupeer-backend.onrender.com</span>'),
    # Two rungs spent, so the ring shows the ramp rather than four blanks.
    ('class="avatar__arc" cx="13" cy="13" r="12" stroke-dashoffset="0"',
     'class="avatar__arc is-on" cx="13" cy="13" r="12" stroke-dashoffset="0"'),
    ('class="avatar__arc" cx="13" cy="13" r="12" stroke-dashoffset="-20.42"',
     'class="avatar__arc is-on" cx="13" cy="13" r="12" stroke-dashoffset="-20.42"'),
    ('<span class="tog" aria-hidden="true">', '<span class="tog" data-on="true" aria-hidden="true">'),
    ('<span data-value="top8">top 8</span>', '<span data-value="top8" data-on="true">top 8</span>'),
    ('<span data-value="flagged">flagged</span>',
     '<span data-value="flagged" data-on="false">flagged</span>'),
    # The context strip, with a file open and the preview disclosed.
    ('id="fileName">no file open<', 'id="fileName">demo.py<'),
    ('<span class="ctx__dot" id="ctxDot" aria-hidden="true"></span>',
     '<span class="ctx__dot is-live" id="ctxDot" aria-hidden="true"></span>'),
    ('<span class="ctx__sep" id="ctxSep" aria-hidden="true" hidden>', '<span class="ctx__sep" id="ctxSep" aria-hidden="true">'),
    ('<span class="ctx__symbol" id="ctxSymbol"></span>',
     '<span class="ctx__symbol" id="ctxSymbol">last_index</span>'),
    ('<span id="focusRange" class="ctx__range"></span>',
     '<span id="focusRange" class="ctx__range">12\u201319</span>'),
    ('<span id="langChip" class="chip" hidden></span>',
     '<span id="langChip" class="chip">Python</span>'),
    ('<button id="ctxOpen" class="btn btn--ghost btn--sm">Open a file</button>',
     '<button id="ctxOpen" class="btn btn--ghost btn--sm" hidden>Open a file</button>'),
    ('title="Show or hide the code preview" disabled>', 'title="Show or hide the code preview">'),
    ('<div class="ctx__code" id="ctxCode" hidden>', '<div class="ctx__code" id="ctxCode">'),
    ('<pre id="codeSnippet" class="ctx__pre" tabindex="0"></pre>',
     PREVIEW_LINES),
    ('<span class="ctx__more" id="ctxMore"></span>',
     '<span class="ctx__more" id="ctxMore">3 more lines</span>'),
    ('<button id="scopeToggle" class="btn btn--ghost btn--sm" aria-pressed="false" hidden>',
     '<button id="scopeToggle" class="btn btn--ghost btn--sm" aria-pressed="false">'),
    # The footer ledger, with something in it.
    ('<span class="ledger__streak" id="streakChip" hidden>',
     '<span class="ledger__streak" id="streakChip">'),
    ('<span id="streakDays">0</span>', '<span id="streakDays">3</span>'),
    ('<span class="ledger__dot" id="ledgerSep" aria-hidden="true" hidden>',
     '<span class="ledger__dot" id="ledgerSep" aria-hidden="true">'),
    ('id="badgesWrap" aria-expanded="false" aria-controls="badgesSheet" disabled>',
     'id="badgesWrap" aria-expanded="false" aria-controls="badgesSheet">'),
    ('<span id="badgeCount">No badges yet</span>', '<span id="badgeCount">7 badges</span>'),
    # Reviewed at the width it ships at.
    ("<body>", '<body style="width:400px;height:780px;border:1px solid #504770">'),
]


def main() -> int:
    src = SRC.read_text(encoding="utf-8")
    start = src.index("<!DOCTYPE html>")
    html = src[start:src.index("</html>`", start) + len("</html>")]

    html = re.sub(r'<meta http-equiv="Content-Security-Policy"[^>]*>', "", html)
    html = re.sub(r'<script nonce="\$\{nonce\}"[^>]*></script>', "", html)

    missed = [find for find, _ in SUBSTITUTIONS if find not in html]
    for find, repl in SUBSTITUTIONS:
        html = html.replace(find, repl, 1)

    html = html.replace("</head>", VSCODE_STUBS + "</head>", 1)

    OUT.write_text(html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + NOTE, 1), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    if missed:
        # Loud rather than silent: a substitution that stops matching means the
        # markup moved, and the preview is quietly no longer what ships.
        print("MARKUP MOVED — these no longer match getHtml():")
        for m in missed:
            print(f"  {m[:78]}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
